import { GLTF } from "three/examples/jsm/loaders/GLTFLoader"

interface GLTFAction extends THREE.AnimationClip {
    name: ActionName;
  }

export type GLTFResult = GLTF & {
    nodes: {
      BlackHorse1: THREE.Mesh
      BlackHorse2: THREE.Mesh
      defaultMaterial021: THREE.Mesh
      defaultMaterial021_1: THREE.Mesh
      BlackKnight1: THREE.Mesh
      BlackKnight2: THREE.Mesh
      BlackPawn1: THREE.Mesh
      BlackPawn2: THREE.Mesh
      BlackPawn3: THREE.Mesh
      BlackPawn4: THREE.Mesh
      BlackPawn5: THREE.Mesh
      BlackPawn6: THREE.Mesh
      BlackPawn7: THREE.Mesh
      BlackPawn8: THREE.Mesh
      BlackQueen: THREE.Mesh
      BlackRock1: THREE.Mesh
      BlackRock2: THREE.Mesh
      defaultMaterial011: THREE.Mesh
      defaultMaterial012: THREE.Mesh
      defaultMaterial035: THREE.Mesh
      defaultMaterial009: THREE.Mesh
      WhiteHorse1: THREE.Mesh
      WhiteHorse2: THREE.Mesh
      WhiteKing: THREE.Mesh
      WhiteKnight1: THREE.Mesh
      WhiteKnight2: THREE.Mesh
      WhitePawn1: THREE.Mesh
      WhitePawn2: THREE.Mesh
      WhitePawn3: THREE.Mesh
      WhitePawn4: THREE.Mesh
      WhitePawn5: THREE.Mesh
      WhitePawn6: THREE.Mesh
      WhitePawn7: THREE.Mesh
      WhitePawn8: THREE.Mesh
      WhiteQueen: THREE.Mesh
      WhiteRock1: THREE.Mesh
      WhiteRock2: THREE.Mesh
      defaultMaterial042_cell031: THREE.Mesh
      defaultMaterial042_cell031_1: THREE.Mesh
      defaultMaterial042_cell013_1: THREE.Mesh
      defaultMaterial042_cell013_2: THREE.Mesh
      defaultMaterial042_cell014: THREE.Mesh
      defaultMaterial042_cell014_1: THREE.Mesh
      defaultMaterial042_cell019: THREE.Mesh
      defaultMaterial042_cell016_1: THREE.Mesh
      defaultMaterial042_cell016_2: THREE.Mesh
      defaultMaterial042_cell022: THREE.Mesh
      defaultMaterial042_cell026: THREE.Mesh
      defaultMaterial042_cell019_1: THREE.Mesh
      defaultMaterial042_cell019_2: THREE.Mesh
      defaultMaterial042_cell020_1: THREE.Mesh
      defaultMaterial042_cell020_2: THREE.Mesh
      defaultMaterial042_cell021_1: THREE.Mesh
      defaultMaterial042_cell021_2: THREE.Mesh
      defaultMaterial042_cell017: THREE.Mesh
      defaultMaterial042_cell023_1: THREE.Mesh
      defaultMaterial042_cell023_2: THREE.Mesh
      defaultMaterial042_cell024_1: THREE.Mesh
      defaultMaterial042_cell024_2: THREE.Mesh
      defaultMaterial042_cell024: THREE.Mesh
      defaultMaterial042_cell025: THREE.Mesh
      defaultMaterial042_cell027: THREE.Mesh
      defaultMaterial041_cell127: THREE.Mesh
      defaultMaterial041_cell127_1: THREE.Mesh
      defaultMaterial041_cell128: THREE.Mesh
      defaultMaterial041_cell128_1: THREE.Mesh
      defaultMaterial041_cell100: THREE.Mesh
      defaultMaterial041_cell100_1: THREE.Mesh
      defaultMaterial041_cell101: THREE.Mesh
      defaultMaterial041_cell101_1: THREE.Mesh
      defaultMaterial041_cell077: THREE.Mesh
      defaultMaterial041_cell078: THREE.Mesh
      defaultMaterial041_cell105: THREE.Mesh
      defaultMaterial041_cell105_1: THREE.Mesh
      defaultMaterial041_cell090: THREE.Mesh
      defaultMaterial041_cell107_1: THREE.Mesh
      defaultMaterial041_cell107_2: THREE.Mesh
      defaultMaterial041_cell108: THREE.Mesh
      defaultMaterial041_cell108_1: THREE.Mesh
      defaultMaterial041_cell109_1: THREE.Mesh
      defaultMaterial041_cell109_2: THREE.Mesh
      defaultMaterial041_cell109: THREE.Mesh
      defaultMaterial041_cell111: THREE.Mesh
      defaultMaterial041_cell112: THREE.Mesh
      defaultMaterial041_cell112_1: THREE.Mesh
      defaultMaterial041_cell113: THREE.Mesh
      defaultMaterial041_cell113_1: THREE.Mesh
      defaultMaterial041_cell114: THREE.Mesh
      defaultMaterial041_cell114_1: THREE.Mesh
      defaultMaterial041_cell115: THREE.Mesh
      defaultMaterial041_cell115_1: THREE.Mesh
      defaultMaterial041_cell116: THREE.Mesh
      defaultMaterial041_cell116_1: THREE.Mesh
    }
    materials: {
      ['Material.011']: THREE.MeshStandardMaterial
      ['Material.016']: THREE.MeshStandardMaterial
      ['Material.014']: THREE.MeshStandardMaterial
      ['Material.015']: THREE.MeshStandardMaterial
      ['Material.012']: THREE.MeshStandardMaterial
      ['Material.007']: THREE.MeshStandardMaterial
      ['Material.006']: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
      ['Material.009']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      ['Material.003']: THREE.MeshStandardMaterial
      ['Material.004']: THREE.MeshStandardMaterial
      ['Material.005']: THREE.MeshStandardMaterial
      ['Material.013']: THREE.MeshStandardMaterial
      ['Material.010']: THREE.MeshStandardMaterial
      ['Material.008']: THREE.MeshStandardMaterial
      initialShadingGroup: THREE.MeshStandardMaterial
      blinn3SG: THREE.MeshStandardMaterial
    }
    animations:GLTFAction[]
  }

  type ActionName =
  | 'Sketchfab_model_Sketchfab_model'
  | 'Collada visual scene group'
  | 'blackpieces_mesh'
  | 'defaultMaterial.005'
  | 'defaultMaterial.044'
  | 'defaultMaterial.018'
  | 'defaultMaterial.050'
  | 'defaultMaterial.049'
  | 'defaultMaterial.014'
  | 'defaultMaterial.013'
  | 'defaultMaterial.003'
  | 'defaultMaterial.002'
  | 'defaultMaterial.001'
  | 'defaultMaterial.015'
  | 'defaultMaterial.016'
  | 'defaultMaterial.017'
  | 'defaultMaterial.051'
  | 'defaultMaterial.033'
  | 'defaultMaterial.052'
  | 'chessboard_mesh'
  | 'defaultMaterial.011'
  | 'defaultMaterial.012'
  | 'whitepieces_mesh'
  | 'defaultMaterial.035Action.001'
  | 'defaultMaterial.009Action'
  | 'defaultMaterial.038'
  | 'defaultMaterial.020'
  | 'defaultMaterial.007'
  | 'defaultMaterial.006'
  | 'defaultMaterial.008'
  | 'defaultMaterial.046'
  | 'defaultMaterial.045'
  | 'defaultMaterial.043'
  | 'defaultMaterial.042'
  | 'defaultMaterial.041'
  | 'defaultMaterial.034'
  | 'defaultMaterial.040'
  | 'defaultMaterial.036'
  | 'defaultMaterial.047'
  | 'defaultMaterial.010'
  | 'defaultMaterial.042_cell.012Action'
  | 'Action'
type GLTFActions = Record<ActionName, THREE.AnimationAction>