/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Chess.glb -types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}
type GLTFResult = GLTF & {
  nodes: {
    BlackBishopTwoPiece: THREE.Mesh
    BlackKingPiece: THREE.Mesh
    BlackKnighTwoPiece: THREE.Mesh
    BlackPawnBishopPiece: THREE.Mesh
    BlackPawnEightPiece: THREE.Mesh
    BlackPawnFivePiece: THREE.Mesh
    BlackPawnFourPiece: THREE.Mesh
    BlackPawnKnightPiece: THREE.Mesh
    BlackPawnOnePiece: THREE.Mesh
    BlackPawnSevenPiece: THREE.Mesh
    BlackPawnSixPiece: THREE.Mesh
    BlackPawnThreePiece: THREE.Mesh
    BlackPawnTwoPiece: THREE.Mesh
    BlackRookOnePiece: THREE.Mesh
    BlackQueenPiece: THREE.Mesh
    BlackRookTwoPiece: THREE.Mesh
    defaultMaterial012_1: THREE.Mesh
    defaultMaterial012_2: THREE.Mesh
    WhiteBishopOnePiece: THREE.Mesh
    WhiteBishopTwoPiece: THREE.Mesh
    WhiteKingPiece: THREE.Mesh
    WhiteKnightOnePiece: THREE.Mesh
    WhiteKnightTwoPiece: THREE.Mesh
    WhitePawnEightPiece: THREE.Mesh
    WhitePawnFivePiece: THREE.Mesh
    WhitePawnFourPiece: THREE.Mesh
    WhitePawnOnePiece: THREE.Mesh
    WhitePawnSevenPiece: THREE.Mesh
    WhitePawnSixPiece: THREE.Mesh
    WhitePawnThreePiece: THREE.Mesh
    WhitePawnTwoPiece: THREE.Mesh
    WhiteQueenPiece: THREE.Mesh
    WhiteRookOnePiece: THREE.Mesh
    WhiteRookTwoPiece: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    blinn3SG: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
  }, animations:GLTFAction[]
}

type ActionName = 'Sketchfab_model' | 'Collada visual scene group' | 'BlackPieces' | 'BlackBishopTwoPiece' | 'BlackKingPiece' | 'BlackKnighTwoPiece' | 'BlackPawnBishopPiece' | 'BlackPawnEightPiece' | 'BlackPawnFivePiece' | 'BlackPawnFourPiece' | 'BlackPawnKnightPiece' | 'BlackPawnOnePiece' | 'BlackPawnSevenPiece' | 'BlackPawnSixPiece' | 'BlackPawnThreePiece' | 'BlackPawnTwoPiece' | 'BlackRookOnePiece' | 'BlackQueenPiece' | 'BlackRookTwoPiece' | 'chessboard' | 'defaultMaterial.012' | 'WhitePieces' | 'WhiteBishopOnePiece' | 'WhiteBishopTwoPiece' | 'WhiteKingPiece' | 'WhiteKnightOnePiece' | 'WhiteKnightTwoPiece' | 'WhitePawnEightPiece' | 'WhitePawnFivePiece' | 'WhitePawnFourPiece' | 'WhitePawnOnePiece' | 'WhitePawnSevenPiece' | 'WhitePawnSixPiece' | 'WhitePawnThreePiece' | 'WhitePawnTwoPiece' | 'WhiteQueenPiece' | 'WhiteRookOnePiece' | 'WhiteRookTwoPiece'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Chessboard(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/Chess.glb') as GLTFResult
  
  return (
    <group  {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
            <group name="BlackPieces">
              <mesh name="BlackBishopTwoPiece" castShadow receiveShadow geometry={nodes.BlackBishopTwoPiece.geometry} material={materials['Material.002']} position={[-3.97, 0, 4.02]} />
              <mesh name="BlackKingPiece" castShadow receiveShadow geometry={nodes.BlackKingPiece.geometry} material={materials['Material.003']} />
              <mesh name="BlackKnighTwoPiece" castShadow receiveShadow geometry={nodes.BlackKnighTwoPiece.geometry} material={materials['Material.001']} position={[0, 0, 0.01]} />
              <mesh name="BlackPawnBishopPiece" castShadow receiveShadow geometry={nodes.BlackPawnBishopPiece.geometry} material={materials['Material.005']} position={[-9.97, 0, 4.02]} />
              <mesh name="BlackPawnEightPiece" castShadow receiveShadow geometry={nodes.BlackPawnEightPiece.geometry} material={materials['Material.015']} position={[1.99, 0, 3.99]} />
              <mesh name="BlackPawnFivePiece" castShadow receiveShadow geometry={nodes.BlackPawnFivePiece.geometry} material={materials['Material.012']} position={[-3.98, 0, 3.97]} />
              <mesh name="BlackPawnFourPiece" castShadow receiveShadow geometry={nodes.BlackPawnFourPiece.geometry} material={materials['Material.011']} position={[-5.98, 0, 3.97]} />
              <mesh name="BlackPawnKnightPiece" castShadow receiveShadow geometry={nodes.BlackPawnKnightPiece.geometry} material={materials['Material.006']} position={[-9.98, 0, 0]} />
              <mesh name="BlackPawnOnePiece" castShadow receiveShadow geometry={nodes.BlackPawnOnePiece.geometry} material={materials['Material.008']} position={[-11.98, 0, 3.97]} />
              <mesh name="BlackPawnSevenPiece" castShadow receiveShadow geometry={nodes.BlackPawnSevenPiece.geometry} material={materials['Material.014']} position={[0.01, 0, 3.99]} />
              <mesh name="BlackPawnSixPiece" castShadow receiveShadow geometry={nodes.BlackPawnSixPiece.geometry} material={materials['Material.013']} position={[-1.97, 0, 3.99]} />
              <mesh name="BlackPawnThreePiece" castShadow receiveShadow geometry={nodes.BlackPawnThreePiece.geometry} material={materials['Material.010']} position={[-8, 0, 3.97]} />
              <mesh name="BlackPawnTwoPiece" castShadow receiveShadow geometry={nodes.BlackPawnTwoPiece.geometry} material={materials['Material.009']} position={[-9.97, 0, 3.97]} />
              <mesh name="BlackRookOnePiece" castShadow receiveShadow geometry={nodes.BlackRookOnePiece.geometry} material={materials['Material.007']} position={[0.03, -0.02, -0.04]} rotation={[Math.PI, 0, Math.PI]} />
              <mesh name="BlackQueenPiece" castShadow receiveShadow geometry={nodes.BlackQueenPiece.geometry} material={materials['Material.004']} />
              <mesh name="BlackRookTwoPiece" castShadow receiveShadow geometry={nodes.BlackRookTwoPiece.geometry} material={materials.Material} position={[13.97, -0.02, -0.04]} rotation={[Math.PI, 0, Math.PI]} />
            </group>
            <group name="chessboard">
              <group name="defaultMaterial012" position={[0, 0.02, 0]}>
                <mesh name="defaultMaterial012_1" castShadow receiveShadow geometry={nodes.defaultMaterial012_1.geometry} material={materials.blinn3SG} />
                <mesh name="defaultMaterial012_2" castShadow receiveShadow geometry={nodes.defaultMaterial012_2.geometry} material={materials['Material.016']} />
              </group>
            </group>
            <group name="WhitePieces">
              <mesh name="WhiteBishopOnePiece" castShadow receiveShadow geometry={nodes.WhiteBishopOnePiece.geometry} material={nodes.WhiteBishopOnePiece.material} position={[-5.99, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
              <mesh name="WhiteBishopTwoPiece" castShadow receiveShadow geometry={nodes.WhiteBishopTwoPiece.geometry} material={nodes.WhiteBishopTwoPiece.material} rotation={[Math.PI, 0, Math.PI]} />
              <mesh name="WhiteKingPiece" castShadow receiveShadow geometry={nodes.WhiteKingPiece.geometry} material={nodes.WhiteKingPiece.material} />
              <mesh name="WhiteKnightOnePiece" castShadow receiveShadow geometry={nodes.WhiteKnightOnePiece.geometry} material={nodes.WhiteKnightOnePiece.material} rotation={[-Math.PI, 0, -Math.PI]} />
              <mesh name="WhiteKnightTwoPiece" castShadow receiveShadow geometry={nodes.WhiteKnightTwoPiece.geometry} material={nodes.WhiteKnightTwoPiece.material} position={[10.02, 0, 0]} rotation={[-Math.PI, 0, -Math.PI]} />
              <mesh name="WhitePawnEightPiece" castShadow receiveShadow geometry={nodes.WhitePawnEightPiece.geometry} material={nodes.WhitePawnEightPiece.material} position={[5.97, 0, -3.99]} />
              <mesh name="WhitePawnFivePiece" castShadow receiveShadow geometry={nodes.WhitePawnFivePiece.geometry} material={nodes.WhitePawnFivePiece.material} position={[0, 0, -3.99]} />
              <mesh name="WhitePawnFourPiece" castShadow receiveShadow geometry={nodes.WhitePawnFourPiece.geometry} material={nodes.WhitePawnFourPiece.material} position={[-1.98, 0, -3.99]} />
              <mesh name="WhitePawnOnePiece" castShadow receiveShadow geometry={nodes.WhitePawnOnePiece.geometry} material={nodes.WhitePawnOnePiece.material} position={[-7.98, 0, -4.11]} />
              <mesh name="WhitePawnSevenPiece" castShadow receiveShadow geometry={nodes.WhitePawnSevenPiece.geometry} material={nodes.WhitePawnSevenPiece.material} position={[4.01, 0, -3.99]} />
              <mesh name="WhitePawnSixPiece" castShadow receiveShadow geometry={nodes.WhitePawnSixPiece.geometry} material={nodes.WhitePawnSixPiece.material} position={[2, 0, -3.99]} />
              <mesh name="WhitePawnThreePiece" castShadow receiveShadow geometry={nodes.WhitePawnThreePiece.geometry} material={nodes.WhitePawnThreePiece.material} position={[-3.98, 0, -3.99]} />
              <mesh name="WhitePawnTwoPiece" castShadow receiveShadow geometry={nodes.WhitePawnTwoPiece.geometry} material={nodes.WhitePawnTwoPiece.material} position={[-6, 0, -3.99]} />
              <mesh name="WhiteQueenPiece" castShadow receiveShadow geometry={nodes.WhiteQueenPiece.geometry} material={nodes.WhiteQueenPiece.material} position={[-2.03, 0, 0]} rotation={[Math.PI, 0, Math.PI]} />
              <mesh name="WhiteRookOnePiece" castShadow receiveShadow geometry={nodes.WhiteRookOnePiece.geometry} material={nodes.WhiteRookOnePiece.material} position={[-13.96, -0.05, -0.05]} />
              <mesh name="WhiteRookTwoPiece" castShadow receiveShadow geometry={nodes.WhiteRookTwoPiece.geometry} material={nodes.WhiteRookTwoPiece.material} position={[0.05, -0.05, -0.05]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Chess.glb')
